api_pet_type:
    type:     rest
    resource: App\Controller\API\PetTypeController
    prefix: /{version}
    requirements:
        version: v\d+

api_contact:
    type:     rest
    resource: App\Controller\API\ContactController
    prefix: /{version}
    requirements:
        version: v\d+
