# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        default_format: json
    versioning: true
#    versioning:
#        enabled: true
#        resolvers:
#            query: false # Query parameter: ?version=v1
#            custom_header: true # X-Accept-Version header
#            media_type: # Accept header
#                enabled: true
#                regex: '/(v|version)=(?P<version>[0-9\.]+)/'
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
