fos_elastica:
    clients:
        default: { host: %env(ELASTICSEARCH_HOST)%, port: %env(ELASTICSEARCH_PORT)% }
    serializer:
        serializer: jms_serializer
    indexes:
        app_v1:
            types:

                contact:
                    persistence:
                        driver: orm
                        model: App\Entity\Contact
                        listener: ~

                location:
                    persistence:
                        driver: orm
                        model: App\Entity\Location
                        listener: ~

                pet_type:
                    persistence:
                        driver: orm
                        model: App\Entity\Pet\PetType
                        listener: ~

                pet_characteristic:
                    persistence:
                        driver: orm
                        model: App\Entity\Pet\PetCharacteristic
                        listener: ~

                pet_characteristic_value:
                    persistence:
                        driver: orm
                        model: App\Entity\Pet\PetCharacteristicValue
                        listener: ~

                pet:
                    properties:
                        id: ~
                        name: ~
                        description: ~
                        status: ~
                        characteristics:
                            type: "nested"
                            properties:
                                id: ~
                                value: ~
                                characteristic:
                                    type: "nested"
                                    properties:
                                        id: ~
                                        name: ~
                    persistence:
                        driver: orm
                        model: App\Entity\Pet\Pet
                        listener: ~
